### ISSUE TITLE
你说了这么多，倒是写几行代码给我们看看呀？

### ISSUE THREAD

**Issue by micli** [qwas982/Chinese-characters-programme-or-use-Mandarin#1]
Github 是免费，但是不是让你拿来浪费的。

**Comment by qwas982** [comment]
你自己要解读为免费，那是你自己的事情啊，
据我所知，free 好像还可以翻译为 自由 的呢，

**Comment by micli** [comment]
我不解读，Github 网页上也没有任何地方提到free 这个词。
但是Github 是全世界的程序员分享代码的地方这一点是确定无疑的。你如果没有代码可以分享，要么就默默地看着少说话，要么就fork 别人的项目好好向别人学习争取以后可以向别人分享你的代码。

Github 的资源有限，不是让你拿来肆意浪费的。

**Comment by qwas982** [comment]
你未免太自我感觉良好了,哪凉快哪呆着去吧.
